server:
 port: 8081

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/expense_auth?useSSL=false&serverTimezone=UTC
  username: root
  password: root

 jpa:
  hibernate: 
   ddl-auto: update
  show-sql: true
  properties: 
   hibernate: 
    format_sql: true
